image: maven:3.9.11-eclipse-temurin-21

stages:
  - build

cache:
  paths:
    - .m2/repository

build-job:
  stage: build

  script:
    - echo "Building Document Approval System..."
    - mvn clean package -DskipTests

  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week