stages:
  - build
  - deploy

build-image:

  stage: build
  tags:
    - ec2

  only:
    - main

  script:

    - echo "Building Docker Image"

    - docker build -t $IMAGE_NAME:latest .

    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

    - docker push $IMAGE_NAME:latest

deploy:

  stage: deploy

  tags:
    - ec2

  script:

    - echo "Deploying Latest Image"

    - cd /home/ubuntu/apps/das

    - docker compose pull

    - docker compose up -d

    - docker image prune -f