stages:
  - build

build-image:
  stage: build

  tags:
    - ec2

  script:
    - echo "Running on EC2 Self Hosted Runner"
    - whoami
    - pwd
    - hostname
    - docker version
    - docker info
    - docker build -t das-test:latest .
    - docker images