package com.company.das.pdf.service.impl;

import java.io.File;
import java.io.IOException;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import com.company.das.common.exception.ResourceNotFoundException;
import com.company.das.document.entity.Document;
import com.company.das.document.repository.DocumentRepository;
import com.company.das.documentversion.entity.DocumentVersion;
import com.company.das.documentversion.repository.DocumentVersionRepository;
import com.company.das.pdf.service.PdfService;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;

import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.layout.properties.TextAlignment;


import lombok.RequiredArgsConstructor;

import com.itextpdf.layout.element.LineSeparator;
import com.itextpdf.kernel.pdf.canvas.draw.SolidLine;

import com.itextpdf.layout.element.Paragraph;


import java.nio.file.Files;

import org.springframework.core.io.ByteArrayResource;
import org.springframework.core.io.Resource;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;

@Service
@RequiredArgsConstructor
public class PdfServiceImpl implements PdfService {
	
	private final DocumentRepository documentRepository;

	private final DocumentVersionRepository documentVersionRepository;

    @Value("${app.pdf.storage-path}")
    private String storagePath;
    
    private DocumentVersion getCurrentDocumentVersion(Long documentId) {

        Document document = documentRepository.findById(documentId)
                .orElseThrow(() ->
                new ResourceNotFoundException("Document not found"));

        return documentVersionRepository
                .findByDocumentAndIsCurrentTrue(document)
                .orElseThrow(() ->
                new ResourceNotFoundException("Current document version not found"));

    }

    @Override
    public String generateDocumentPdf(Document document,
                                      Integer versionNumber) {

        try {

            String documentFolder = storagePath
                    + File.separator
                    + document.getDocumentNumber();

            File folder = new File(documentFolder);

            if (!folder.exists()) {
                folder.mkdirs();
            }

            String pdfPath = documentFolder
                    + File.separator
                    + "version-" + versionNumber + ".pdf";

            PdfWriter writer = new PdfWriter(pdfPath);

            PdfDocument pdf = new PdfDocument(writer);

            com.itextpdf.layout.Document pdfDocument =
                    new com.itextpdf.layout.Document(pdf);
            
            
  

         // ====================== HEADER ======================

            Paragraph heading = new Paragraph("DOCUMENT APPROVAL SYSTEM")
                    .simulateBold()
                    .setFontSize(20)
                    .setTextAlignment(TextAlignment.CENTER);

            pdfDocument.add(heading);

            Paragraph subHeading = new Paragraph("Office Document Clearance & Approval Workflow")
                    .setFontSize(11)
                    .setFontColor(ColorConstants.DARK_GRAY)
                    .setTextAlignment(TextAlignment.CENTER);

            pdfDocument.add(subHeading);

            pdfDocument.add(new Paragraph("\n"));
            
            
            pdfDocument.add(new Paragraph(document.getDocumentContent())
                    .setFontSize(12)
                    .setMultipliedLeading(1.5f));
            
            
            pdfDocument.add(new Paragraph("\n"));

            pdfDocument.add(new LineSeparator(new SolidLine()));

            pdfDocument.add(new Paragraph("\n"));

            Paragraph footer = new Paragraph("Generated by Document Approval System")
                    .setFontSize(10)
                    .simulateItalic()
                    .setTextAlignment(TextAlignment.CENTER);

            pdfDocument.add(footer);

            Paragraph version = new Paragraph("Version : " + versionNumber)
                    .setFontSize(10)
                    .setTextAlignment(TextAlignment.CENTER);

            pdfDocument.add(version);

            pdfDocument.close();

            return pdfPath;

        } catch (IOException e) {

            throw new RuntimeException("Unable to generate PDF", e);

        }

    }
    
    @Override
    public ResponseEntity<Resource> viewPdf(Long documentId) {

        try {

            DocumentVersion version = getCurrentDocumentVersion(documentId);

            File file = new File(version.getPdfPath());

            if (!file.exists()) {
                throw new RuntimeException("PDF file not found");
            }

            ByteArrayResource resource =
                    new ByteArrayResource(Files.readAllBytes(file.toPath()));

            return ResponseEntity.ok()
                    .header(HttpHeaders.CONTENT_DISPOSITION,
                            "inline; filename=\"" + file.getName() + "\"")
                    .contentType(MediaType.APPLICATION_PDF)
                    .contentLength(file.length())
                    .body(resource);

        } catch (IOException e) {

            throw new RuntimeException("Unable to read PDF file", e);

        }

    }
    
    @Override
    public ResponseEntity<Resource> downloadPdf(Long documentId) {

        try {

            DocumentVersion version = getCurrentDocumentVersion(documentId);

            File file = new File(version.getPdfPath());

            if (!file.exists()) {
                throw new RuntimeException("PDF file not found");
            }

            ByteArrayResource resource =
                    new ByteArrayResource(Files.readAllBytes(file.toPath()));

            return ResponseEntity.ok()
                    .header(HttpHeaders.CONTENT_DISPOSITION,
                            "attachment; filename=\"" + file.getName() + "\"")
                    .contentType(MediaType.APPLICATION_PDF)
                    .contentLength(file.length())
                    .body(resource);

        } catch (IOException e) {

            throw new RuntimeException("Unable to read PDF file", e);

        }

    }

}